version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5435:5435"
    environment:
      POSTGRES_DB: 'newspaper'
      POSTGRES_USER: 'streje'
      POSTGRES_PASSWORD: 'secret'
    volumes:
      - ./DB/var/pgdata:/var/lib/postgresql/data
      - ./DB/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  database_data:
    driver: local