server:
  port: 8081
  servlet:
    context-path: /api
jwt:
  secret: dajksljn4322odnsakkl231jljdljsakigposojjkwkjjiojaddsad9989
  lifetime: 5h
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/newspaper
    username: postgres
    password: 123SOMBIO321 
  jpa:
    show-sql: false
    properties:
      hibernate:
        ddl-auto: create-drop
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non-contextual-creation: true
  main:
    allow-circular-references: true